resources/conf/settings.toml, resources/templates/base.html, resources/templates/funding.html, resources/templates/launch.html
Keeps it enabled as long as there is any ETH on the account. Also changed the wording to indicate that RDN does not be 100% funded to be able to launch
=> Always display the 'Convert to ETH' button

raiden_installer/__init__.py, raiden_installer/tokens.py
added the current ServiceToken of contracts 0.33. as RDN and changed the Wiz to use the Goerli settings
=> Quick changes to make the Wiz work on Goerli

raiden_installer/web.py
Rather than relying on port 8080 being free, detect a free port. We also log a message that the web app is running and where, in case the automatic opening of the browser fails.
Fixes #36 
Fixes #57 
Fixes #85
=> Use a detected free port for the web app

raiden_installer/ethereum_rpc.py, raiden_installer/utils.py, raiden_installer/web.py, resources/templates/raiden_setup.html, tests/unit.py
- Accept the endpoint url from Infura's dashboard in place of the project id. In theory, this should already have worked, but the html template had a validation method that rejected inputs longer than 32 bytes. Also, the urls copied from the Infura dashboard are missing the scheme, so the wizard would not accept them.
- Make sure on each launch with a new configuration that the given Eth RPC provider is responsive. This is done in particular to cope with wrong (valid but inexistant) Infura project ids.
Fixes #83 
Fixes #44
=> Infura-related fixes

tools/pyinstaller/raiden_webapp.spec
Temporarily adding 'pkg_resources.py2_warn' to the hidden imports
=> Fix issue with latest setuptools version #95

resources/templates/funding.html
The gas price used by web3.js in the frontend is using `eth_gasPrice` RPC. It might be the case that the underlying ETH node is choosing the slow gas price resulting in long waiting periods. As a quick fix, before funding the frontend will fetch the `ethgasstation.info` endpoint and use fast gas price for faster transaction times. 
In the future, it might make sense to get rid of the third party query.
=> fetch gas price from ethgasstation

raiden_installer/__init__.py, raiden_installer/tokens.py, raiden_installer/web.py, resources/conf/mainnet.toml, resources/templates/base.html, resources/templates/launch.html
Calls Coinmarketcaps APIs to convert the cryptocurrencies to USD. The API key is my personal one need to see if raiden has to have a different key. Unfortunately modify the serverside because Coinmarketcap does not send CORs headers to protect the API keys and also advises to call through the server side of the application.
Ran into merge conflicts with pull request #119 hence opening new pull request.
=> Calling CoinmarketAPI's for currency conversion

raiden_installer/tokens.py, raiden_installer/web.py
Response is like this 
```
{
"exchange": "kyber",
"currency": "RDN",
"target_amount": 10,
"as_wei": 14426829418305688,
"formatted": "0.0144 ETH",
"utc_seconds": 1588245104
}
```
solves #133
=> Cost estimation post request

raiden_installer/token_exchange.py
Solves  #141
Uniswap successfully completes the swap but gets `0 DAI`. looking into the matter.
```
python -m raiden_installer.web
2020-05-04 18:37.31 Starting web server
2020-05-04 18:37.31 Installer page ready on http://localhost:1994
2020-05-04 18:37.31 Should open automatically in browser...
2020-05-04 18:37.51 Generating new wallet and configuration file for raiden
2020-05-04 18:37.53 Redirecting to /account/config-0x5f793f7678123dB5b4AaBFd9Ca25dfa049A615b5-mainnet.toml
2020-05-04 18:38.51 Waiting for confirmation of transaction 0x4acb1a7245d1f89aeb30e98e30bc128274d4c50dbdd81ac5d81df4fed819aee4
2020-05-04 18:39.21 Transaction confirmed
2020-05-04 18:39.21 Redirecting to /swap/config-0x5f793f7678123dB5b4AaBFd9Ca25dfa049A615b5-mainnet.toml/RDN
2020-05-04 18:39.41 Starting swap at …
```
=> Changing SAI to DAI for uniswap

raiden_installer/__init__.py, raiden_installer/token_exchange.py, raiden_installer/tokens.py, raiden_installer/utils.py, raiden_installer/web.py, resources/conf/mainnet.toml, resources/templates/account.html, resources/templates/base.html
Fixes #142
Replaces the old eth_required_amount with two new thresholds. One ETH threshold (`eth_required`) to execute the swaps and on ETH threshold (`eth_required_after_swap`) to start Raiden
=> Adds eth_amount_required_after_swap and changes eth_required

raiden_installer/token_exchange.py, raiden_installer/transactions.py
The transactions for depositing the UDC did not have any gas price set.
=> higher gas price for depositing UDC

tools/pyinstaller/raiden_webapp.spec
As long as their is no own window application for the wizard it should not be bundled as an app for mac builds. Otherwise there will be no terminal open to shut down the wizard which would make it very hard for non-technical users to do so.
=> remove app bundle for mac

raiden_installer/constants.py, raiden_installer/ethereum_rpc.py, raiden_installer/token_exchange.py, raiden_installer/transactions.py, raiden_installer/utils.py, raiden_installer/web.py
This PR focusses mainly on the reduction of the waiting time for the user. Several optimizations have been made. 
To make it more convinient for the user the RDN tokens will directly be sent to the UDC after swapping ETH to RDN. This happens automatically while the user is waiting for the swap to be done. After the succesful RDN swap the RDNs are already stored in the UDC.
I wrote my own gas price strategy which simply takes only 25 blocks instead of 120 to calculate the price from. This reduces buildung the transaction from ~1 minuten down to 16 seconds. Additionally for the short term I included fetching the gas price from ethgasstion. This is done in a matter of milliseconds. As a fallback my own gas price strategy including a margin of 35% is used. 
I also included @palango s PR in …
=> Merge UDC into RDN Swap, make transactions faster

raiden_installer/ethereum_rpc.py
This is a little fix to create a faster gas price calculation
=> add web3 cache for faster gas price calculation

raiden_installer/token_exchange.py
This is an attempt that `estimate_gas` won't recalculate the gas price
=> do not calculate gas price upon estimate

Makefile, tools/docker/build.Dockerfile
This PR includes a docker build and make command to create a wizard binary built on debian-stretch base. This is the linux version which is supported by raiden also.
To create the binary just run: 
`make bundle-docker` 
You are gonna find in directory `dist` a tar called `raiden_wizard_linux.tar.gz` containing an executable.
Now, the enduser does not need to mark the binary as executable anymore and just run it
=> Docker build to create a binary for debian-stretch

raiden_installer/transactions.py, raiden_installer/web.py, requirements.txt
This also removes the `ethtoken` dependency, which was incompatible with other dependencies.
=> Update dependenices (raiden-contracts, etc...)

raiden_installer/utils.py, raiden_installer/web.py
There is a problem with the `XDG_DATA_DIRS` inside a PyInstaller package.
This leads to the `webbrowser.open_new` call not working.
This commit mangles the `LD_LIBRARY_PATH`, which fixes the problem.
See: https://github.com/pyinstaller/pyinstaller/issues/3668 for some
reference.
=> Fix LD_LIBRARY_PATH for PyInstaller

raiden_installer/web.py, resources/templates/swap.html
This changes the SWAP buttons, if there were any errors during the cost estimation. It is expected to relieve most of the pain of #269 .
=> Selectively disable failing swap buttons

raiden_installer/__init__.py, raiden_installer/raiden.py, raiden_installer/tokens.py, raiden_installer/transactions.py, raiden_installer/utils.py, raiden_installer/web.py, resources/conf/goerli.toml, resources/static/css/app.css, resources/static/css/app.scss, resources/templates/account.html, resources/templates/account_password.html, resources/templates/base.html, resources/templates/configuration_list.html, resources/templates/index.html
This PR makes the new wizard usable on goerli testnet. It adds an selector on the first page to let the user choose to use Mainnet or Goerli.
=> Make Goerli work again

Makefile, tools/docker/build.Dockerfile, tools/pyinstaller/raiden_webapp.spec
We decided to have separate binaries for the two versions of the Wizard.
=> Configure build to output one binary for mainnet and one for goerli

raiden_installer/__init__.py, raiden_installer/base.py, raiden_installer/network.py, raiden_installer/raiden.py, raiden_installer/shared_handlers.py, raiden_installer/tokens.py, raiden_installer/web.py, raiden_installer/web_testnet.py, resources/conf/demo_env.toml
closes #283 
This PR makes the testnet wizard using the demoenv. Additionally when starting the webserver for goerli or mainnet it uses a hardcoded settings file. It should not be possible to change the settings by the user when the application started, because we want to reduce the decisions that a user has to make.
This PR fixes the problem that the wizard expected the settings file to be named like the network. This prevented from having two configurations for goerli.
=> Use demoenv for testnet wizard

resources/conf/mainnet.toml
Close #331 
Somehow the Wizard was always generating a config with local routing and no one ever realized this. This makes the Wizard using the PFS when creating a config.
=> Use PFS on mainnet

.circleci/config.yml
This introduces a change in the CI cache keys to invalidate old caches. This is necessary because of the Codecov security breach (https://github.com/raiden-network/team/issues/933).
=> Introduce versioning for CircleCI cache key to invalidate old caches

CHANGELOG.md, resources/static/js/account.js, resources/static/js/base.js, resources/templates/account.html
Fixes #338 
MetaMask removed the injected `window.web3` object recently, which we relied on. This broke our integration of MetaMask.
MetaMask should now be used through the `window.ethereum` API, which is specified by EIP 1193. This PR migrates the frontend to use this API to make the transaction request. The only place where we send a transaction from the frontend is for funding the user account.
This uses a small library (`@metamask/detect-provider`) to detect the rpc provider as recommended by MetaMask.
=> frontend: Migrate to use the new MetaMask API 

CHANGELOG.md, resources/conf/demo_env.toml, resources/conf/mainnet.toml
Updates the Wizard to download the binary of the new Bespin release.
=> Use Raiden client version v2.0.0

README.md, resources/templates/terms.html
As our documentation was completely moved to readthedocs, this updates all links to it.
=> Update docs links to use readthedocs

CHANGELOG.md, raiden_installer/shared_handlers.py, resources/static/js/account.js, resources/templates/account.html, resources/templates/index.html
Reverts raiden-network/raiden-wizard#340
The bug on the Ramp widget was fixed by them. We didn't want to release the integration because of the bug. Now we can do so.
The code was reviewed already and does not need another check.
=> Revert "Remove Ramp Network integration"

resources/static/css/app.css, resources/static/css/app.scss, resources/static/js/account.js, resources/static/js/base.js, resources/templates/account.html
A user who wants to buy more than the required amount of ETH cannot do this with Ramp, because the Ramp widget prohibits to change the value we pass through the API. By letting the user change the value beforehands, we can circumvent this restriction.
This adds an input field where a user can specify how much ETH they want to buy. If a user selects less than the required amount, an error is shown. The field is prefilled with the required amount, so there is no additional step if the user does not want to modify it.
As the functionality for changing the value of the tx in MetaMask is quite hidden, I decided to use the input field for both options.
=> Add input field on account page for increasing ETH amount

CHANGELOG.md
Needed to get develop up-to-date with master. The additional commits are here because an earlier release was rebased into master. These release PRs should only be merged with merge commits.
=> Get Release v1.3.0 into develop
