raideninstaller/steps/eth_client.py, raideninstaller/utils.py, requirements-dev.txt
Introduces one more if condition for yes/no input parsing
=> Add condition to include yes/no input

installer/base.py, installer/cli/app.py
Görli Network uses the raiden workshop faucets
Add Ropsten Network class, and fund method using their own faucet
=> Add method to fund accounts using Goerli and Ropsten faucets

raiden_installer/base.py, raiden_installer/web/app.py, raiden_installer/web/templates/index.html
Refined installer progress messages and added an exception handler for detecting if the Raiden process has died.
=> Progress message changes and bug fix

raiden_installer/base.py, raiden_installer/web/app.py, raiden_installer/web/templates/index.html
Changing setup form to always use PFS.
=> Updates needed to get nightly from single-purpose build.

raiden_installer/__init__.py, raiden_installer/base.py, requirements.txt, tools/build_static_binary.sh
Updating version of raiden contracts that will be used + revert version of raiden being downloaded
=> Updates to use latest testnet release

raiden_installer/__init__.py, raiden_installer/base.py, raiden_installer/network.py, raiden_installer/raiden.py, raiden_installer/tokens.py, raiden_installer/web.py, resources/templates/index.html, resources/templates/raiden_setup.html, tests/__init__.py, tests/manual.py
This PR includes a minimal working version of the launch page for mainnet:
- connect to user's Metamask to transfer mainnet ETH
- poll for mainnet ETH and tokens
- Enable obtaining RDN and SAI via Kyber and Uniswap
Closes #90 
Closes #91 
Closes #92
=> Enable mainnet funding

raiden_installer/account.py, raiden_installer/base.py, raiden_installer/raiden.py, raiden_installer/tokens.py, raiden_installer/web.py, requirements.txt, resources/conf/mainnet.toml
=> Latest changes to work with 0.200.0-rc8

raiden_installer/raiden.py, raiden_installer/web.py
=> Add raiden /status check before WebUI

raiden_installer/web.py, resources/templates/account.html
This PR gives a download link to download the keystore file directly from the browser. It is intended to be a backup for the user in case of something breaks
=> download keystore

raiden_installer/token_exchange.py
fixes to accept altready calculated costs as an argument
=> fix buy tokens

raiden_installer/token_exchange.py
there was an error in calculating the gas limit
=> fix gas estimation

raiden_installer/transactions.py
There was a wrong representation of gas price. Needs to be in `Wei` not `EthereumAmount`
=> fix gas price representation

resources/static/css/app.css, resources/static/css/app.scss, resources/templates/account.html, resources/templates/base.html
To redirect the user to the swap page if they have enough ETH
=> Fixes detection of ETH balance on account page

raiden_installer/tokens.py, raiden_installer/web.py
Two bugs are fixed
it shows now: 
- trying to acquire X DAI
-  it shows X DAI available
- it shows the actual costs of the transaction
fixes #169 and #180
=> Fix info text exchange process

resources/templates/swap.html
=> Adding tooltip help in the swap RDN DAI

raiden_installer/base.py, raiden_installer/ethereum_rpc.py, raiden_installer/raiden.py, raiden_installer/web.py, resources/templates/account_unlock.html
- Don't store passphrases on disk, instead use a global variable in the tornado webapp
- Query user for unlock passphrase, if passphrase not (yet) available
Fixes #189
=> passphrase in RAM and unlock page

raiden_installer/base.py
fix a bug if the folder for storing the passphrase is not created yet
=> fix missing folder when storing passphrase

raiden_installer/web.py
Before it was listening on all 0.0.0.0
=> webserver to listen only on localhost

raiden_installer/ethereum_rpc.py, raiden_installer/web.py, resources/templates/account.html, resources/templates/base.html
There is an GET endpoint to ask for the current gas price. This removes the necissity for the frontend to ask 3rd parites
=> gas price endpoint

raiden_installer/utils.py
=>  bugfix time

resources/templates/account.html
The variable was declared twice which caused the error
=> gas price fetching from Backend

resources/static/css/app.css, resources/templates/account.html
Gives an explanation for 0.18 ETH
=> Explanation for the 0.18 ETH

resources/templates/account.html
=> Consolidating all tooltips for account.html page

raiden_installer/web.py, resources/templates/base.html
Shows a link to Etherscan while transferring ETH to the raiden account
=> Show link to etherscan for the transaction hash

raiden_installer/token_exchange.py, resources/conf/mainnet.toml, resources/templates/swap.html
Change that only one amount can be swapped which is 
- 10 RDN
- 3 DAI
- ETH Required 1.1 ETH
- ETH after swap 0.075
=> Swap only one amount

resources/conf/mainnet.toml
=> add eth amount required to 0.125 ETH

resources/templates/account.html, resources/templates/account_password.html, resources/templates/base.html
closes #212 
Shows the default browser alert when user presses back button or reload.
=> Show alert when back button is pressed

resources/templates/account.html, resources/templates/account_password.html, resources/templates/index.html, resources/templates/launch.html
Delets tooltip from page 1 and page 7 (launch)
=> Adds explanatory bullet points to pages 2 and 4

raiden_installer/ethereum_rpc.py
This was the same error as raiden-network/raiden#6165 mostly took the code from that solution and adapted it to the wizard
=> fix infura get block returning None

resources/templates/base.html
=> Get full video data by forced http request

requirements.txt, tools/docker/build.Dockerfile
To remove `pyinstaller` from the wizard package.
=> Remove pyinstaller dep, add it to Dockerfile

resources/conf/mainnet.toml
=> Pointing the Wizard to Alderaan

Makefile
Build make target for mac build.
=> Add make target for mac build

raiden_installer/shared_handlers.py, raiden_installer/web.py, raiden_installer/web_testnet.py, resources/static/css/app.css, resources/static/css/app.scss, resources/templates/account.html, resources/templates/configuration_list.html, resources/templates/index.html
We want to split the logic of mainnet and goerli more to have cleaner code. This PR splits them into separate webservers. 
We also decided to have two binaries, one for mainnet and one for goerli. This PR makes that also easier.
=>  Refactor mainnet and testnet functionalities into separate webservers 

resources/templates/index.html
The disclaimer does not need to be shown on the Goerli Wizard.
=> Only show disclaimer on mainnet

raiden_installer/__init__.py, raiden_installer/base.py, raiden_installer/shared_handlers.py, raiden_installer/web.py, raiden_installer/web_testnet.py, tests/unit/test_base.py, tests/unit/test_tokens.py
Solves #284 
I tried to reduce passing the settings name around but a name is still used to identify a settings object / file.
=> Only load config files that match the settings

raiden_installer/shared_handlers.py, raiden_installer/web.py, raiden_installer/web_testnet.py, resources/templates/swap.html
=> Pro-actively detect whether user acquires tokens and move to the next step

resources/static/css/app.css, resources/static/css/app.scss, resources/static/js/swap.js, resources/templates/account.html, resources/templates/swap.html
Closes #315 
User should just select the exchange as we only have one swap amount now. It doesn't make sense to have the extra click. The confirm button stays.
=> Merge exchange selection and amount buttons in swap page

Makefile
Ignore errors when cleaning up.
=> Fix clean command

raiden_installer/shared_handlers.py, resources/static/js/raiden_setup.js, resources/templates/raiden_setup.html, tests/integration/test_web.py, tests/unit/test_ethereum_rpc.py
Closes #186 , closes #279 , closes #318
=> Small fix ups related to Infura

CHANGELOG.md
Get the changelog update also into develop.
=>  Get Release v1.1.0 into develop

raiden_installer/shared_handlers.py, resources/static/js/account.js, resources/templates/account.html, resources/templates/index.html
At the moment Ramp has a bug which makes it not possible to use it in the Wizard. This is why we decided to not have it in the current release.
The commit can be reverted once Ramp is fixed.
=> Remove Ramp Network integration
